### ISSUE TITLE
JSON Object to MQTT Message Conversion

### ISSUE THREAD

**Issue by baqwas** [arduino-libraries/Arduino_JSON#10]
Hello,

This is a newbie request for guidance. When I use the following code:
```

JSONVar _message_;
_message_["status"] = 1;
client.publish(topic, _message_); // publish to MQTT broker
```

The broker displays _message_ as an empty string. Bottom line, is there some function/method to transform a JSON object to a string before use downstream. (Defeats the purpose of JSON, I know, but the use is external to board's sketch). Thanks.

Kind regards.

**Comment by baqwas** [comment]
Sorry for logging this. Problem solved with **stringify** and **strcpy**. Thanks.

Kind regards.

**Comment by manchoz** [comment]
@baqwas 

```C++
JSONVar _message_;
_message_["status"] = 1;
String payload = JSON.stringify(_message_);
client.publish(topic, payload.c_str());
```
