### ISSUE TITLE
Como posso jogar o valor de um JSONVar em uma String?

### ISSUE THREAD

**Issue by WellingtonSouzaAbreu** [arduino-libraries/Arduino_JSON#27]
Olá.

Esse é o meu dilema: 
String resultado = myObject["result"];

Pode me ajudar?

**Comment by per1234** [comment]
Hi @WellingtonSouzaAbreu. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there:

https://forum.arduino.cc/c/international/portugues/51
