### ISSUE TITLE
  operator unsigned long() const; is missing

### ISSUE THREAD

**Issue by dirkx** [arduino-libraries/Arduino_JSON#39]
The declaration for:

```cpp
operator unsigned long() const;
```

appears to be missing

**Comment by aentinger** [comment]
Hi @dirkx ☕ :wave:

I'm not deeply familiar with this code base. Where do you think its missing? Can you provide a PR to fix this?

Cheers, Alex

**Comment by dirkx** [comment]
Why I think it is missing -- because the analog of

	unsigned int = json["key1"];

for an unsigned long is:L

	unsigned long foo = json["key2"];

and that will fail without it :) Will see if I can do a one line PR.

Dw.
