### ISSUE TITLE
How get the values from Jason Array which contains multiple values

### ISSUE THREAD

**Issue by rjrajbir** [arduino-libraries/Arduino_JSON#42]
Hi, there I am working on a project where I have to get data after hitting API and show data on screen.
I am using this lib and getting the data properly when the data is coming simple as JSON var.
but now data is coming in JSON array
For eg.

```cpp
const char inpu2[} = {"medicines": [
        
        {
            "medicine_name": "Paracetamol",
            "instruction": "In case of fever",
            "medicine_start_date": "2022-08-09",
            "medicine_end_date": "2022-08-15",
            "t1": "08:00:00",
            "t2": "",
            "t3": "16:00:00",
            "t4": ""
        },
        {
            "medicine_name": "Crocin",
            "instruction": "Body Pain",
            "medicine_start_date": "2022-08-09",
            "medicine_end_date": "2022-08-10",
            "t1": "08:00:00",
            "t2": "",
            "t3": "",
            "t4": ""
        }
    ]
};
```

Please help me how to get this data

Regards
Rajbir

**Comment by per1234** [comment]
Hi @rjrajbir. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/c/using-arduino/programming-questions/20
