### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by Zhu-jiatong** [arduino-libraries/Arduino_JSON#44]
When will there be a new release (in the Arduino IDE library manager)?

**Comment by aentinger** [comment]
Hi @Zhu-jiatong :coffee: :wave:

[Here](https://github.com/arduino-libraries/Arduino_JSON/releases/tag/0.2.0) you've got it :wink: :bow: .

**Comment by Zhu-jiatong** [comment]
The update is not available from the IDE’s library manager.

Best regards,
