### ISSUE TITLE
Migrating from Ver 0.1.0 to 0.2.0 generates error

### ISSUE THREAD

**Issue by ninora** [arduino-libraries/Arduino_JSON#46]
Hi there,
Following code works just fine with 0.1.0:
```
JSONVar dataJson;
dataJson["a"] = "aaa";
String myString = JSON.stringify(dataJson);
dataJson = JSON.parse(myString);
String someData;
someData = dataJson["a"];

```
And generates an error with 0.2.0: 
**error: ambiguous overload for 'operator=' (operand types are 'arduino::String' and 'JSONVar')**

Thanks!

**Comment by aentinger** [comment]
This does ring a bell because I recall fixing an example somewhere that head this error. Can't find the example though anymore and it was apparently no in this repository. You can help this with an explicit cast.

**Comment by aentinger** [comment]
Found it: Here you go: https://github.com/arduino-libraries/MKRGSM/commit/f990e64f7b9cbd993d62ece3e6325c47a71af051

**Comment by ninora** [comment]
This solved the problem, thanks
