### ISSUE TITLE
ESP32 crash when all keys are removed from an object 

### ISSUE THREAD

**Issue by Stefino76** [arduino-libraries/Arduino_JSON#51]
When I have an object with some keys and setting a value to undefined can remove that key and value from the object. If I set to undefined all the object keys the ESP32 crash and reebot with error in serial monitor:
`Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.`
If I leave at least one key for the object I can remove the others without any error.

**Comment by per1234** [comment]
Hi @Stefino76. Thanks for your report.

Please provide a minimal sketch that produces the fault.

**Comment by Stefino76** [comment]
I have tried to reproduce the issue in another sketch and I can't. I think there's another problem in my code and no in the library. So I close the issue at moment.
